/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as base from "./base";
export type { base };
export type { EVMUniversalNFT } from "./EVMUniversalNFT";
export type { EVMUniversalToken } from "./EVMUniversalToken";
export type { ZetaChainUniversalNFT } from "./ZetaChainUniversalNFT";
export type { ZetaChainUniversalToken } from "./ZetaChainUniversalToken";
