/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as base from "./base";
export { EVMUniversalToken__factory } from "./EVMUniversalToken__factory";
export { ZetaChainUniversalToken__factory } from "./ZetaChainUniversalToken__factory";
