"""add_nft_collections_table

Revision ID: 9aeb2ac0bdaf
Revises: c584bd34490e
Create Date: 2025-04-02 16:08:16.485398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aeb2ac0bdaf'
down_revision = 'c584bd34490e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 