/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { UniversalNFT__factory } from "./UniversalNFT__factory";
export { UniversalToken__factory } from "./UniversalToken__factory";
