"""add_testnet_column

Revision ID: 2a3b4c5d6e7f
Revises: 50f6cdd89cb3
Create Date: 2023-04-07 12:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '2a3b4c5d6e7f'
down_revision = '50f6cdd89cb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('token_deployments')]
    
    if 'testnet' not in columns:
        op.add_column(
            'token_deployments', 
            sa.Column('testnet', sa.Boolean(), nullable=False, server_default=sa.text('true'))
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_deployments', 'testnet')
    # ### end Alembic commands ### 