"""add_verification_status_column

Revision ID: 1a2b3c4d5e6f
Revises: 9aeb2ac0bdaf
Create Date: 2025-04-03 19:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '1a2b3c4d5e6f'
down_revision = '9aeb2ac0bdaf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('token_deployments')]
    
    if 'verification_status' not in columns:
        op.add_column(
            'token_deployments', 
            sa.Column('verification_status', sa.String(), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_deployments', 'verification_status')
    # ### end Alembic commands ### 